---
- name: "Deploy a JBoss EAP"
  hosts: jboss
  become: true
  vars:
    eap_apply_cp: true
    eap_version: 7.4.0
    eap_offline_install: false
    eap_config_base: 'standalone-full-ha.xml'
    eap_driver_module_name: 'org.postgresql'
    eap_driver_version: 9.4.1212
    eap_driver_jar_filename: "postgresql-{{ eap_driver_version }}.jar"
    eap_driver_jar_url: "https://repo.maven.apache.org/maven2/org/postgresql/postgresql/{{ eap_driver_version }}/{{ eap_driver_jar_filename }}"
    eap_enable_yml_config: True
    eap_yml_configs:
      - eap_configuration.yml.j2
    app:
      name: 'addressbook.war'
      url: 'https://gpte-public.s3.amazonaws.com/addressbook.war'
  collections:
    - redhat.eap
  roles:
    - eap_install
    - eap_systemd
  tasks:
    - name: "Set up for JBoss module"
      include_role:
        name: eap_driver
    - name: "Ensures webapp {{ app.name }} has been retrieved from {{ app.url }}"
      get_url:
        url: "{{ app.url }}"
        dest: "/opt/jboss_eap/jboss-eap-7.4/{{ app.name }}"
    - name: "Deploy webapp"
      include_role:
        name: eap_utils
        tasks_from: jboss_cli.yml
      vars:
        jboss_cli_query: "'deploy --force /opt/jboss_eap/jboss-eap-7.4/{{ app.name }}'"
  post_tasks:
    - include_tasks: validate.yml
      loop: 
        - "8080"